#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

const ROOT = process.env.ROOT || '/docker/openspg';
const CSV_DIR = path.join(ROOT, 'exports/owa_ontology/v1');
const MAX_FRAME_BYTES = 1_048_576;

const OPTIMAKB_URL = process.env.OPTIMAKB_MCP_URL || 'https://optima.kag.taxbell.pl/mcp';
const OPTIMAKB_KEY = process.env.OPTIMAKB_API_KEY || '';
const EXA_KEY = process.env.EXA_API_KEY || '';
const OPENSPG_COOKIE_FILE = process.env.OPENSPG_COOKIE_FILE || '/etc/erp-kb-openspg.cookie';

function loadCsv(fileName) {
  const filePath = path.join(CSV_DIR, fileName);
  if (!fs.existsSync(filePath)) return [];
  const data = fs.readFileSync(filePath, 'utf8').replace(/\r/g, '');
  const rows = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < data.length; i += 1) {
    const ch = data[i];
    current += ch;
    if (ch === '"') {
      if (inQuotes && data[i + 1] === '"') { current += data[i + 1]; i += 1; }
      else { inQuotes = !inQuotes; }
    } else if (ch === '\n' && !inQuotes) { rows.push(current.slice(0, -1)); current = ''; }
  }
  if (current) rows.push(current);
  if (rows.length < 2) return [];
  const headers = parseCsvLine(rows[0]);
  return rows.slice(1).map((line) => {
    const values = parseCsvLine(line);
    const row = {};
    headers.forEach((header, index) => { row[header] = values[index] ?? ''; });
    return row;
  });
}

function parseCsvLine(line) {
  const values = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') { current += '"'; i += 1; }
      else { inQuotes = !inQuotes; }
    } else if (ch === ',' && !inQuotes) { values.push(current); current = ''; }
    else { current += ch; }
  }
  values.push(current);
  return values.map((v) => v.startsWith('"') && v.endsWith('"') ? v.slice(1, -1).replace(/""/g, '"') : v);
}

function csvEscape(value) {
  const normalized = value == null ? '' : String(value);
  if (/[",\n\r]/.test(normalized)) return `"${normalized.replace(/"/g, '""')}"`;
  return normalized;
}

function csvLine(values) {
  return values.map(csvEscape).join(',');
}

function writeInboxDraft(entityId, canonicalName, description, mainTable) {
  const dateDir = new Date().toISOString().slice(0, 10).replace(/-/g, '-');
  const inboxDir = path.join(ROOT, 'downloads', 'knowledge_inbox', dateDir);
  fs.mkdirSync(inboxDir, { recursive: true });
  const hex = crypto.randomBytes(4).toString('hex');
  const slug = String(canonicalName || 'entity').normalize('NFKD').replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').toLowerCase().slice(0, 40);
  const draftId = `draft_${dateDir.replace(/-/g, '-')}_${hex}_owa-auto-${slug}`;
  const jsonPath = path.join(inboxDir, `${draftId}.json`);
  const mdPath = path.join(inboxDir, `${draftId}.md`);
  const created = new Date().toISOString();
  const json = {
    id: draftId,
    kbName: 'OWA Platform Optima Ontology',
    kbNamespace: 'OWAOntology',
    title: `Encja: ${canonicalName}`,
    tags: ['OWA', 'ontologia', 'optima', slug, 'auto-learned'],
    metadata: { discoveredVia: 'owa_ontology_mcp', sourceTier: 'ontology', retrievedAt: created },
    createdAt: created,
  };
  const md = `# Encja: ${canonicalName}

## Status weryfikacji
- Status: \`częściowo-zweryfikowane\`
- Identyfikator ontologiczny: \`OWAOntology.${canonicalName.replace(/\s/g, '')}\`

## Opis biznesowy
${description || ''}

## Źródła danych
| Rola źródła | Schemat | Tabela lub obiekt | Status | Dowód |
|---|---|---|---|---|
| Tabela główna | \`CDN\` | \`${mainTable || 'UNKNOWN'}\` | \`CONFIRMED\` | MSSQL + OWA Ontology MCP |

## Metadane
- Ontologia: OWA
- Namespace: OWAOntology
- Auto-generated by OWAOntology MCP v2.0.0
`;
  fs.writeFileSync(jsonPath, JSON.stringify(json, null, 2), 'utf8');
  fs.writeFileSync(mdPath, md, 'utf8');
  return { draftId, jsonPath, mdPath };
}

let ontologyEntities = loadCsv('ontology_entity.csv');
let ontologyFields = loadCsv('ontology_field.csv');
let ontologyRelations = loadCsv('ontology_relation.csv');
let workflowPatterns = loadCsv('workflow_pattern.csv');
const chunks = loadCsv('chunk.csv');

function reloadStats() {
  ontologyEntities = loadCsv('ontology_entity.csv');
  ontologyFields = loadCsv('ontology_field.csv');
  ontologyRelations = loadCsv('ontology_relation.csv');
  workflowPatterns = loadCsv('workflow_pattern.csv');
  return { entities: ontologyEntities.length, fields: ontologyFields.length, relations: ontologyRelations.length, workflows: workflowPatterns.length, chunks: chunks.length };
}

function getStats() {
  return { entities: ontologyEntities.length, fields: ontologyFields.length, relations: ontologyRelations.length, workflows: workflowPatterns.length, chunks: chunks.length };
}

function appendToCsv(fileName, values) {
  const filePath = path.join(CSV_DIR, fileName);
  const line = csvLine(values);
  fs.appendFileSync(filePath, `\n${line}`, 'utf8');
}

function rewriteCsv(fileName, headers, rows) {
  const filePath = path.join(CSV_DIR, fileName);
  const tmpPath = `${filePath}.${process.pid}.tmp`;
  const content = [headers.join(','), ...rows.map((r) => csvLine(r))].join('\n') + '\n';
  fs.writeFileSync(tmpPath, content, 'utf8');
  fs.renameSync(tmpPath, filePath);
}

function generateEntityId(name) {
  const slug = String(name || 'entity').normalize('NFKD').replace(/[^\w\s]/g, '').replace(/\s+/g, '_').toUpperCase().slice(0, 80);
  const hex = crypto.randomBytes(4).toString('hex');
  return `OWA_ENTITY_${slug}_${hex}`;
}

function generateItemId(prefix, entityName, suffix) {
  const slug = String(entityName || 'item').normalize('NFKD').replace(/[^\w\s]/g, '').replace(/\s+/g, '_').toUpperCase().slice(0, 40);
  const hex = crypto.randomBytes(4).toString('hex');
  return `${prefix}_${slug}_${suffix}_${hex}`;
}

const ENTITY_HEADERS = ['id', 'name', 'description', 'semanticType', 'canonicalName', 'ontologyId', 'verificationStatus', 'confidenceLevel', 'businessDomain', 'mainTable', 'mcpReadTools', 'mcpWriteTools', 'aliases', 'summary'];
const FIELD_HEADERS = ['id', 'name', 'description', 'semanticType', 'entityRefId', 'fieldName', 'mssqlColumn', 'mcpField', 'sqlType', 'nullable', 'keyRole', 'mappingStatus', 'summary'];
const RELATION_HEADERS = ['id', 'name', 'description', 'semanticType', 'sourceEntityRefId', 'targetEntityRefId', 'predicate', 'cardinality', 'relationType', 'joinCondition', 'status', 'summary'];
const WORKFLOW_HEADERS = ['id', 'name', 'description', 'semanticType', 'workflowName', 'sourceEntityRefId', 'targetEntityRefId', 'mcpTool', 'mode', 'status', 'summary'];

const serverInfo = {
  name: 'owa-ontology',
  version: '2.0.0',
  description: 'Self-learning MCP server for the OWA Platform Optima Ontology — research, map, and extend.',
  stats: getStats(),
};

function normalize(value) { return String(value || '').toLowerCase().replace(/\s+/g, ' ').trim(); }

function matchesSearch(row, query) {
  if (!query) return true;
  const terms = normalize(query).split(/\s+/).filter(Boolean);
  if (!terms.length) return true;
  const searchText = Object.values(row).map((v) => normalize(String(v ?? ''))).join(' ');
  for (const term of terms) {
    if (!searchText.includes(term)) return false;
  }
  return true;
}

function writeMessage(message) {
  const payload = JSON.stringify(message);
  process.stdout.write(`Content-Length: ${Buffer.byteLength(payload, 'utf8')}\r\n\r\n${payload}`);
}

function readJsonRpcRequest(buffer) {
  const headerEnd = buffer.indexOf('\r\n\r\n');
  if (headerEnd === -1) return null;
  const header = buffer.slice(0, headerEnd).toString('utf8');
  const match = header.match(/Content-Length:\s*(\d+)/i);
  if (!match) return null;
  const length = Number(match[1]);
  if (length > MAX_FRAME_BYTES) return null;
  const total = headerEnd + 4 + length;
  if (buffer.length < total) return null;
  try {
    const body = buffer.slice(headerEnd + 4, total).toString('utf8');
    const request = JSON.parse(body);
    return { request, consumed: total };
  } catch { return null; }
}

function success(id, result) { return { jsonrpc: '2.0', id, result }; }

function entitySummary(row) {
  return { id: row.id, canonicalName: row.canonicalName || row.name, verificationStatus: row.verificationStatus, confidenceLevel: row.confidenceLevel, businessDomain: row.businessDomain, mainTable: row.mainTable, ontologyId: row.ontologyId };
}

function entityFull(row) {
  const entity = entitySummary(row);
  entity.description = row.description || '';
  entity.mcpReadTools = (row.mcpReadTools || '').split(';').map((s) => s.trim()).filter(Boolean);
  entity.mcpWriteTools = (row.mcpWriteTools || '').split(';').map((s) => s.trim()).filter(Boolean);
  entity.aliases = (row.aliases || '').split(';').map((s) => s.trim()).filter(Boolean);
  entity.summary = row.summary || '';
  entity.fields = ontologyFields.filter((f) => f.entityRefId === row.id).map((f) => ({ name: f.name, mssqlColumn: f.mssqlColumn, mcpField: f.mcpField, sqlType: f.sqlType, nullable: f.nullable, keyRole: f.keyRole, mappingStatus: f.mappingStatus, description: f.description }));
  entity.relations = ontologyRelations.filter((r) => r.sourceEntityRefId === row.id).map((r) => ({ predicate: r.predicate, targetEntityRefId: r.targetEntityRefId, cardinality: r.cardinality, relationType: r.relationType, joinCondition: r.joinCondition, status: r.status }));
  entity.workflows = workflowPatterns.filter((w) => w.sourceEntityRefId === row.id).map((w) => ({ name: w.name, mcpTool: w.mcpTool, mode: w.mode, status: w.status, summary: w.summary }));
  return entity;
}

function findEntity(idOrName) {
  const search = normalize(idOrName);
  const exactById = ontologyEntities.find((e) => e.id === idOrName);
  if (exactById) return exactById;
  const exactByName = ontologyEntities.find((e) => normalize(e.name) === search || normalize(e.canonicalName) === search);
  if (exactByName) return exactByName;
  const searchTokens = search.split(/[^a-z0-9_]+/).filter(Boolean);
  if (!searchTokens.length) return null;
  let best = null, bestScore = -1;
  for (const e of ontologyEntities) {
    const entityText = normalize(e.name + ' ' + (e.canonicalName || ''));
    let matchCount = 0, exactWordBonus = 0;
    const words = entityText.split(/[^a-z0-9_]+/).filter(Boolean);
    for (const token of searchTokens) {
      if (entityText.includes(token)) { matchCount += 1; if (words.some((w) => w === token)) exactWordBonus += 1; }
    }
    if (matchCount === searchTokens.length) {
      const score = matchCount * 10 + exactWordBonus * 5 + (1 / Math.max(1, entityText.length));
      if (score > bestScore) { bestScore = score; best = e; }
    }
  }
  return best;
}

async function httpPost(url, headers, body) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 30000);
  try {
    const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(body), signal: controller.signal });
    const text = await response.text();
    try { return JSON.parse(text); } catch { return text; }
  } finally { clearTimeout(timeout); }
}

const requestQueue = [];
let processing = false;
let buffer = Buffer.alloc(0);

async function processQueue() {
  if (processing) return;
  processing = true;
  while (requestQueue.length) {
    const { id, method, params } = requestQueue.shift();
    try {
      let result = null;

      switch (method) {
        case 'initialize': {
          result = { protocolVersion: '2024-11-05', serverInfo: { ...serverInfo, stats: getStats() }, capabilities: { tools: {} } };
          break;
        }

        case 'tools/list': {
          result = { tools: [
            { name: 'list_owa_entities', description: 'List all ontology entities with basic metadata (name, status, main table, confidence).', inputSchema: { type: 'object', properties: { status: { type: 'string', description: 'Filter by verificationStatus' } } } },
            { name: 'get_owa_entity', description: 'Get full entity details: description, fields (MCP→MSSQL mappings), relations, workflows, and chunks.', inputSchema: { type: 'object', properties: { entity: { type: 'string', description: 'Entity id, name, or canonicalName' } }, required: ['entity'] } },
            { name: 'search_owa_ontology', description: 'Search across entities, fields, relations, and workflows for matching text.', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'Search terms (space-separated)' }, limit: { type: 'integer', description: 'Max results (default 10)' } }, required: ['query'] } },
            { name: 'get_owa_field_mappings', description: 'Return MCP→MSSQL field mappings for a given entity.', inputSchema: { type: 'object', properties: { entity: { type: 'string', description: 'Entity id, name, or canonicalName' } }, required: ['entity'] } },
            { name: 'get_owa_workflows', description: 'Return workflow patterns for a given entity, or all if entity=ALL.', inputSchema: { type: 'object', properties: { entity: { type: 'string', description: 'Entity id, name, canonicalName, or ALL' } } } },
            { name: 'get_owa_relations', description: 'Return ontology relations for a given entity, or all if entity=ALL.', inputSchema: { type: 'object', properties: { entity: { type: 'string', description: 'Entity id, name, canonicalName, or ALL' } } } },
            { name: 'get_owa_stats', description: 'Return server statistics: entity, field, relation, workflow, and chunk counts.', inputSchema: { type: 'object', properties: {} } },
            { name: 'ask_erp_knowledge', description: 'Ask the ERP Knowledge MCP (OptimaKB) a question. Returns raw answer with evidence from the ERP KB set.', inputSchema: { type: 'object', properties: { question: { type: 'string', description: 'Natural language question about Comarch ERP Optima' } }, required: ['question'] } },
            { name: 'search_web_knowledge', description: 'Search the web via Exa for information about Optima, ERP, and business topics. Returns title, URL, and snippet.', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'Search query' }, numResults: { type: 'integer', description: 'Number of results (default 5, max 10)' } }, required: ['query'] } },
            { name: 'fetch_web_page', description: 'Fetch and read a full web page via Exa. Use after search_web_knowledge to get full page content.', inputSchema: { type: 'object', properties: { url: { type: 'string', description: 'URL to fetch' }, maxChars: { type: 'integer', description: 'Max characters to return (default 3000)' } }, required: ['url'] } },
            { name: 'add_owa_entity', description: 'Add a new ontology entity. Generates ID automatically. Writes to CSV and memory.', inputSchema: { type: 'object', properties: { name: { type: 'string', description: 'Entity display name' }, canonicalName: { type: 'string', description: 'Canonical entity name' }, mainTable: { type: 'string', description: 'Main MSSQL table (e.g. CDN.Towary)' }, description: { type: 'string', description: 'Business description' }, verificationStatus: { type: 'string', description: 'verification status' }, confidenceLevel: { type: 'string', description: 'wysoki / średni / niski' }, businessDomain: { type: 'string', description: 'Business domain' }, mcpReadTools: { type: 'string', description: 'Semicolon-separated MCP READ tools' }, mcpWriteTools: { type: 'string', description: 'Semicolon-separated MCP WRITE tools' }, aliases: { type: 'string', description: 'Semicolon-separated aliases' }, ontologyId: { type: 'string', description: 'Optional ontology identifier' } }, required: ['name', 'mainTable'] } },
            { name: 'add_owa_fields_batch', description: 'Add multiple field mappings for an entity at once. Writes N rows to CSV in one call.', inputSchema: { type: 'object', properties: { entityRefId: { type: 'string', description: 'Entity ID to add fields to' }, fields: { type: 'array', description: 'Array of {name, mssqlColumn, mcpField, sqlType, nullable, keyRole, mappingStatus, description}', items: { type: 'object' } } }, required: ['entityRefId', 'fields'] } },
            { name: 'add_owa_relation', description: 'Add an ontology relation between two entities.', inputSchema: { type: 'object', properties: { sourceEntityRefId: { type: 'string', description: 'Source entity ID' }, targetEntityRefId: { type: 'string', description: 'Target entity ID (or target entity name)' }, predicate: { type: 'string', description: 'Relation predicate (e.g. MA_POZYCJE)' }, cardinality: { type: 'string', description: '1:N, N:1, N:M, 1:1' }, relationType: { type: 'string', description: 'FK, LOGICAL_JOIN, Asocjacja, Kompozycja' }, joinCondition: { type: 'string', description: 'SQL join condition' }, status: { type: 'string', description: 'CONFIRMED, PARTIAL, etc.' } }, required: ['sourceEntityRefId', 'predicate'] } },
            { name: 'add_owa_workflow', description: 'Add a workflow pattern to an entity.', inputSchema: { type: 'object', properties: { sourceEntityRefId: { type: 'string', description: 'Source entity ID' }, mcpTool: { type: 'string', description: 'MCP tool name' }, mode: { type: 'string', description: 'READ or WRITE' }, name: { type: 'string', description: 'Workflow description' }, targetEntityRefId: { type: 'string', description: 'Optional target entity ID' } }, required: ['sourceEntityRefId', 'mcpTool'] } },
            { name: 'update_owa_entity', description: 'Update an existing entity. Only provided fields are changed.', inputSchema: { type: 'object', properties: { entityId: { type: 'string', description: 'Entity ID to update' }, updates: { type: 'object', description: 'Fields to update (mainTable, description, verificationStatus, confidenceLevel, mcpReadTools, mcpWriteTools, aliases, businessDomain)' } }, required: ['entityId', 'updates'] } },
            { name: 'build_owa_ontology', description: 'Re-export staging CSVs from inbox drafts and optionally force-build to OpenSPG project 16.', inputSchema: { type: 'object', properties: { force: { type: 'boolean', description: 'Force OpenSPG build after export (default false)' }, files: { type: 'string', description: 'Comma-separated CSV files to force-build (default: all changed)' } } } },
          ] };
          break;
        }

        case 'tools/call': {
          const toolName = params?.name;
          const args = params?.arguments ?? {};
          let text = '';

          switch (toolName) {
            case 'list_owa_entities': {
              const statusFilter = normalize(args.status || '');
              const filtered = statusFilter ? ontologyEntities.filter((e) => normalize(e.verificationStatus) === statusFilter) : ontologyEntities;
              text = JSON.stringify({ entities: filtered.map(entitySummary), count: filtered.length, total: ontologyEntities.length }, null, 2);
              break;
            }

            case 'get_owa_entity': {
              const entity = findEntity(args.entity);
              text = entity ? JSON.stringify(entityFull(entity), null, 2) : JSON.stringify({ error: `Entity not found: ${args.entity}`, similar: ontologyEntities.filter((e) => matchesSearch(e, args.entity)).slice(0, 5).map((e) => e.name) }, null, 2);
              break;
            }

            case 'search_owa_ontology': {
              const query = String(args.query || '');
              const limit = Math.max(1, Math.min(Number(args.limit || 10), 50));
              const results = [];
              for (const row of ontologyEntities) { if (matchesSearch(row, query)) results.push({ type: 'entity', ...entitySummary(row) }); }
              for (const row of ontologyFields) { if (results.length >= limit + 10) break; if (matchesSearch(row, query)) results.push({ type: 'field', id: row.id, name: row.name, entityRefId: row.entityRefId, mssqlColumn: row.mssqlColumn, mcpField: row.mcpField, mappingStatus: row.mappingStatus }); }
              for (const row of ontologyRelations) { if (results.length >= limit + 10) break; if (matchesSearch(row, query)) results.push({ type: 'relation', id: row.id, predicate: row.predicate, source: row.sourceEntityRefId, target: row.targetEntityRefId, joinCondition: row.joinCondition }); }
              for (const row of workflowPatterns) { if (results.length >= limit + 10) break; if (matchesSearch(row, query)) results.push({ type: 'workflow', id: row.id, name: row.name, mcpTool: row.mcpTool, sourceEntityRefId: row.sourceEntityRefId }); }
              text = JSON.stringify({ query, results: results.slice(0, limit), totalFound: results.length }, null, 2);
              break;
            }

            case 'get_owa_field_mappings': {
              const entity = findEntity(args.entity);
              if (!entity) { text = JSON.stringify({ error: `Entity not found: ${args.entity}` }, null, 2); break; }
              const fields = ontologyFields.filter((f) => f.entityRefId === entity.id).map((f) => ({ fieldName: f.name, mcpField: f.mcpField, mssqlColumn: f.mssqlColumn, sqlType: f.sqlType, nullable: f.nullable, keyRole: f.keyRole, mappingStatus: f.mappingStatus }));
              text = JSON.stringify({ entity: entity.canonicalName || entity.name, entityId: entity.id, fields, count: fields.length }, null, 2);
              break;
            }

            case 'get_owa_workflows': {
              const entityArg = String(args.entity || '').trim().toUpperCase();
              const rows = entityArg === 'ALL' || !entityArg ? workflowPatterns : workflowPatterns.filter((w) => { const e = findEntity(args.entity); return e && w.sourceEntityRefId === e.id; });
              text = JSON.stringify({ entity: args.entity, workflows: rows, count: rows.length, total: workflowPatterns.length }, null, 2);
              break;
            }

            case 'get_owa_relations': {
              const entityArg = String(args.entity || '').trim().toUpperCase();
              const rows = entityArg === 'ALL' || !entityArg ? ontologyRelations : ontologyRelations.filter((r) => { const e = findEntity(args.entity); return e && r.sourceEntityRefId === e.id; });
              text = JSON.stringify({ entity: args.entity, relations: rows, count: rows.length, total: ontologyRelations.length }, null, 2);
              break;
            }

            case 'get_owa_stats': {
              const statuses = {};
              for (const e of ontologyEntities) { const s = e.verificationStatus || 'unknown'; statuses[s] = (statuses[s] || 0) + 1; }
              text = JSON.stringify({ serverInfo: { ...serverInfo, stats: getStats() }, verificationStatuses: statuses }, null, 2);
              break;
            }

            case 'ask_erp_knowledge': {
              if (!OPTIMAKB_KEY) { text = JSON.stringify({ error: 'OPTIMAKB_API_KEY not configured' }); break; }
              const mcpPayload = { jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'answer_question', arguments: { question: String(args.question || '') } } };
              const response = await httpPost(OPTIMAKB_URL, { 'Authorization': `Bearer ${OPTIMAKB_KEY}` }, mcpPayload);
              text = JSON.stringify({ question: args.question, answer: response }, null, 2);
              break;
            }

            case 'search_web_knowledge': {
              if (!EXA_KEY) { text = JSON.stringify({ error: 'EXA_API_KEY not configured' }); break; }
              const exaPayload = { query: String(args.query || ''), numResults: Math.min(Number(args.numResults || 5), 10), useAutoprompt: true, type: 'auto' };
              const exaResult = await httpPost('https://api.exa.ai/search', { 'x-api-key': EXA_KEY }, exaPayload);
              const results = ((exaResult && exaResult.results) || []).map((r) => ({ title: r.title, url: r.url, snippet: r.text || r.snippet || '', publishedDate: r.publishedDate || '' }));
              text = JSON.stringify({ query: args.query, results, count: results.length }, null, 2);
              break;
            }

            case 'fetch_web_page': {
              if (!EXA_KEY) { text = JSON.stringify({ error: 'EXA_API_KEY not configured' }); break; }
              const maxChars = Number(args.maxChars || 3000);
              const fetchPayload = { urls: [String(args.url || '')], text: true };
              const fetchResult = await httpPost('https://api.exa.ai/contents', { 'x-api-key': EXA_KEY }, fetchPayload);
              const page = (fetchResult && fetchResult.results && fetchResult.results[0]) || {};
              text = JSON.stringify({ url: args.url, title: page.title || '', text: String(page.text || '').slice(0, maxChars), truncated: String(page.text || '').length > maxChars }, null, 2);
              break;
            }

            case 'add_owa_entity': {
              const entityId = generateEntityId(args.name);
              const values = [
                entityId,
                args.name || '',
                args.description || '',
                'ontology_entity',
                args.canonicalName || args.name || '',
                args.ontologyId || '',
                args.verificationStatus || 'częściowo-zweryfikowane',
                args.confidenceLevel || 'średni',
                args.businessDomain || '',
                args.mainTable || '',
                args.mcpReadTools || '',
                args.mcpWriteTools || '',
                args.aliases || '',
                args.summary || `${args.name || ''} — ${args.description || ''}`.slice(0, 1200),
              ];
              appendToCsv('ontology_entity.csv', values);
              const draft = writeInboxDraft(entityId, args.canonicalName || args.name || '', args.description || '', args.mainTable || '');
              reloadStats();
              text = JSON.stringify({ ok: true, action: 'add_owa_entity', entityId, entity: entitySummary(ontologyEntities.find((e) => e.id === entityId) || values.reduce((acc, v, i) => { acc[ENTITY_HEADERS[i]] = v; return acc; }, {})), draft, stats: getStats() }, null, 2);
              break;
            }

            case 'add_owa_fields_batch': {
              const entity = findEntity(args.entityRefId);
              if (!entity) { text = JSON.stringify({ error: `Entity not found: ${args.entityRefId}` }); break; }
              const fields = Array.isArray(args.fields) ? args.fields : [];
              if (!fields.length) { text = JSON.stringify({ error: 'fields array is empty' }); break; }
              const lines = [];
              const added = [];
              for (const f of fields) {
                const fieldId = generateItemId('OWA_FIELD', f.name || f.mssqlColumn || 'field', entity.canonicalName || entity.name);
                const values = [
                  fieldId, f.name || f.mssqlColumn || '', f.description || '', 'ontology_field', entity.id,
                  f.mssqlColumn || '', f.mssqlColumn || '', f.mcpField || '', f.sqlType || '', f.nullable || '', f.keyRole || '',
                  f.mappingStatus || 'PARTIAL', f.summary || '',
                ];
                lines.push(values);
                added.push({ id: fieldId, mssqlColumn: f.mssqlColumn, mcpField: f.mcpField });
              }
              for (const values of lines) appendToCsv('ontology_field.csv', values);
              reloadStats();
              text = JSON.stringify({ ok: true, action: 'add_owa_fields_batch', entityRefId: entity.id, entityName: entity.canonicalName || entity.name, addedCount: added.length, added, stats: getStats() }, null, 2);
              break;
            }

            case 'add_owa_relation': {
              const sourceEntity = findEntity(args.sourceEntityRefId);
              if (!sourceEntity) { text = JSON.stringify({ error: `Source entity not found: ${args.sourceEntityRefId}` }); break; }
              let targetRefId = args.targetEntityRefId || '';
              if (targetRefId && !findEntity(targetRefId)) { const target = ontologyEntities.find((e) => normalize(e.name).includes(normalize(targetRefId))); if (target) targetRefId = target.id; }
              const relId = generateItemId('OWA_REL', args.predicate || 'relation', sourceEntity.canonicalName || sourceEntity.name);
              const values = [relId, args.predicate || '', args.joinCondition || '', 'ontology_relation', sourceEntity.id, targetRefId, args.predicate || '', args.cardinality || '', args.relationType || '', args.joinCondition || '', args.status || 'PARTIAL', args.summary || ''];
              appendToCsv('ontology_relation.csv', values);
              reloadStats();
              text = JSON.stringify({ ok: true, action: 'add_owa_relation', relationId: relId, predicate: args.predicate, source: sourceEntity.id, target: targetRefId, stats: getStats() }, null, 2);
              break;
            }

            case 'add_owa_workflow': {
              const entity = findEntity(args.sourceEntityRefId);
              if (!entity) { text = JSON.stringify({ error: `Entity not found: ${args.sourceEntityRefId}` }); break; }
              const wfId = generateItemId('OWA_WF', args.mcpTool || 'workflow', entity.canonicalName || entity.name);
              const values = [wfId, args.name || args.mcpTool || '', args.name || args.mcpTool || '', 'workflow_pattern', args.name || args.mcpTool || '', entity.id, args.targetEntityRefId || '', args.mcpTool || '', args.mode || 'WRITE', 'WRITE_NOT_CALLED', args.summary || ''];
              appendToCsv('workflow_pattern.csv', values);
              reloadStats();
              text = JSON.stringify({ ok: true, action: 'add_owa_workflow', workflowId: wfId, mcpTool: args.mcpTool, entityId: entity.id, stats: getStats() }, null, 2);
              break;
            }

            case 'update_owa_entity': {
              const entity = ontologyEntities.find((e) => e.id === args.entityId);
              if (!entity) { text = JSON.stringify({ error: `Entity not found: ${args.entityId}` }); break; }
              const updates = args.updates || {};
              for (const key of Object.keys(updates)) {
                if (ENTITY_HEADERS.includes(key) && key !== 'id') entity[key] = String(updates[key] ?? entity[key] ?? '');
              }
              const rows = ontologyEntities.map((e) => (e.id === entity.id ? ENTITY_HEADERS.map((h) => e[h] ?? '') : ENTITY_HEADERS.map((h) => e[h] ?? '')));
              rewriteCsv('ontology_entity.csv', ENTITY_HEADERS, rows);
              reloadStats();
              text = JSON.stringify({ ok: true, action: 'update_owa_entity', entityId: entity.id, canonicalName: entity.canonicalName || entity.name, updated: Object.keys(updates), stats: getStats() }, null, 2);
              break;
            }

            case 'build_owa_ontology': {
              const exportResult = spawnSync(process.execPath, ['scripts/export_owa_ontology.mjs'], { cwd: ROOT, encoding: 'utf8', timeout: 120_000 });
              let exportOk = false, exportData = null;
              try { exportData = JSON.parse(exportResult.stdout || '{}'); exportOk = exportData?.ok === true; } catch { exportData = { error: exportResult.stderr || exportResult.stdout }; }

              let buildResult = null;
              const force = args.force === true;
              if (force) {
                const env = { ...process.env, ROOT, OPENSPG_COOKIE_FILE };
                if (args.files) env.OPENSPG_FORCE_FILES = String(args.files);
                const buildProc = spawnSync(process.execPath, ['scripts/build_owa_ontology.mjs'], { cwd: ROOT, encoding: 'utf8', timeout: 600_000, env });
                buildResult = { status: buildProc.status, stdout: (buildProc.stdout || '').slice(0, 500), stderr: (buildProc.stderr || '').slice(0, 500) };
              }

              reloadStats();
              text = JSON.stringify({ ok: exportOk, export: exportData, build: force ? buildResult : { skipped: true, reason: 'force=false — use force=true to trigger OpenSPG build' }, stats: getStats() }, null, 2);
              break;
            }

            default:
              text = `Unknown tool: ${toolName}`;
          }

          result = { content: [{ type: 'text', text }] };
          break;
        }

        case 'notifications/initialized': break;

        default:
          writeMessage({ jsonrpc: '2.0', id, error: { code: -32601, message: `Method not found: ${method}` } });
          continue;
      }

      if (result !== undefined) writeMessage(success(id, result));
    } catch (error) {
      writeMessage({ jsonrpc: '2.0', id, error: { code: -32603, message: error.message } });
    }
  }
  processing = false;
}

process.stdin.on('data', (chunk) => {
  buffer = Buffer.concat([buffer, chunk]);
  while (true) {
    const parsed = readJsonRpcRequest(buffer);
    if (!parsed) break;
    buffer = buffer.slice(parsed.consumed);
    if (parsed.request.id === undefined && parsed.request.method?.startsWith('notifications')) { writeMessage({ jsonrpc: '2.0', id: null, result: {} }); continue; }
    requestQueue.push(parsed.request);
    processQueue();
  }
});

process.stdin.resume();
